version: '3.8'

services:
  blinko-postgres:
    image: postgres:14
    container_name: blinko-postgres
    networks:
      - blinko-network
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6$7n8mG*j9misp
      TZ: US/New York
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  blinko-website:
    image: blinkospace/blinko:latest
    container_name: blinko-website
    networks:
      - blinko-network
    ports:
      - "1111:1111"
    environment:
      NODE_ENV: production
      NEXTAUTH_SECRET: ${6$7n8mG*j9misp}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    volumes:
      - blinko_data:/app/.blinko
    depends_on:
      - blinko-postgres

networks:
  blinko-network:
    driver: bridge

volumes:
  postgres_data:
  blinko_data:
